Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -12,7 +12,7 @@ on:
       version:
         description: 'Version Identifier'
         required: true
-        default: 'a0.0.0v'      
+        default: '0.0.0'      
 jobs:
   deploy:
 
@@ -27,15 +27,40 @@ jobs:
       uses: actions/setup-python@v2
       with:
         python-version: '3.x'
-    - name: Update Version
-      run: |
-        echo "::error file="TEST",line=0,col=0::test error message"
-        echo ${{ github.event.release.target_commitish }}
+    - name: Install dependencies
+      run: |        
+        python -m pip install --upgrade pip
+        # pip install releasy
+    - name: Identify Version
+      id: ident-version
         TAG=${GITHUB_REF##*/}
+        if ! [[ "${{ github.event.inputs.version }}" == "" ]]; then
+          TAG=${{ github.event.inputs.version }};
+          echo "Push Button Test Deploy:$TAG";
+          echo "::set-output name=TYPE::test"
+        else
+          echo "Release Deploy:$TAG"
+          echo "::set-output name=TYPE::release"
+        fi
+        echo "::set-output name=VERSION::$TAG"
+    - name: Release Step
+      if: ${{ steps.ident-version-id.outputs.TYPE }}==release
+      run: |
+        # echo "::error file="TEST",line=0,col=0::test error message"
+        echo "RELEASING CURRENT BRANCH: ${{ github.event.release.target_commitish }}"
         echo ${{ github.head_ref }}
         sed -i "s/__version__=\".*\"/__version__=\"$TAG\"/" version.txt
-        cat version.txt
+    - name: Test Release Step
+      if: ${{ steps.ident-version-id.outputs.TYPE }}==test
+      run: |
+        # echo "::error file="TEST",line=0,col=0::test error message"
+        echo "TESTING CURRENT BRANCH: ${{ github.event.release.target_commitish }}"
+        echo ${{ github.head_ref }}
+        sed -i "s/__version__=\".*\"/__version__=\"$TAG\"/" version.txt  
+    - name: Recommit Version File
+        echo "Updating VERSION:${{ steps.ident-version-id.outputs.VERSION }}"
+       
         
-    - uses: stefanzweifel/git-auto-commit-action@v4
-      with:
-        commit_message: Deploy Version ${{ github.event.inputs.name }} to PyPi.
+    - name: Cleanup and Commit
+      run: |
+        echo ${{ }}
